#!/usr/bin/env python3
"""
post-tool-use-failure.py -- PostToolUseFailure JSONL logger (Feature 4).

Fires after any tool call returns failure. Cannot block (the tool has already
failed by the time this event arrives -- exit code is purely advisory).

Writes ONE JSON line per failure to .claude/state/failures-YYYY-MM-DD.jsonl
with this shape:

    {
      "ts": "ISO timestamp",
      "tool": "Bash" | "Edit" | "Write" | ...,
      "error": "<error text from Claude Code>",
      "session_id": "<session uuid>",
      "cwd": "<absolute working directory>",
      "mode": "default" | "auto" | ...,
      "tool_input_keys": ["file_path", "old_string", ...]
    }

PRIVACY: only the KEYS of tool_input are logged, not the VALUES. Tool inputs
may contain secrets, file paths inside private/, command strings with API
tokens, etc. Logging only key NAMES preserves the failure-pattern signal
without leaking sensitive content. The error field is logged verbatim
because Claude Code's error text is generated by the harness and does not
typically contain secrets, but reviewers should still keep
.claude/state/failures-*.jsonl out of any external share.

Always exits 0. Always best-effort (any exception swallowed at outer frame).

Pattern inspiration: disler/claude-code-hooks-mastery @ 052ad1cbd5aeb1ec4a1def22012d1293c6225625
  (concept reference only; no code copied; the repo has no declared LICENSE
  so verbatim copy was not viable. The JSONL hook-logger pattern is generic
  and uncopyrightable -- implementation written from scratch for this vault.)
"""
import json
import os
import sys
from datetime import datetime
from pathlib import Path

VAULT_ROOT = Path(os.environ.get("VAULT_ROOT", os.getcwd()))
STATE_DIR = VAULT_ROOT / ".claude" / "state"


def main() -> int:
    # Explicit sys.stdin.read() + json.loads(raw) rather than json.load(sys.stdin):
    # the latter shows intermittent zero-byte reads under Git Bash on Windows
    # (buffered text-mode incremental reads can return early before full pipe
    # payload arrives). Same pattern documented in subagent-telemetry.py.
    try:
        raw = sys.stdin.read()
        if not raw.strip():
            return 0  # empty payload; nothing to log
        payload = json.loads(raw)
    except (json.JSONDecodeError, ValueError, OSError):
        return 0  # silent-pass on malformed stdin

    tool_input = payload.get("tool_input", {}) or {}
    record = {
        "ts": datetime.now().isoformat(timespec="milliseconds"),
        "tool": payload.get("tool_name", ""),
        "error": payload.get("error", ""),
        "session_id": payload.get("session_id", ""),
        "cwd": payload.get("cwd", ""),
        "mode": payload.get("permission_mode", ""),
        # PRIVACY: log KEY NAMES only, never values
        "tool_input_keys": sorted(tool_input.keys()) if isinstance(tool_input, dict) else [],
    }

    try:
        STATE_DIR.mkdir(parents=True, exist_ok=True)
        log_path = STATE_DIR / f"failures-{datetime.now().date().isoformat()}.jsonl"
        with log_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")
    except OSError:
        pass  # best-effort
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception:
        # Outer safety net: any exception is suppressed and we exit 0.
        sys.exit(0)
