#!/usr/bin/env python3
"""Generate BOOTSTRAP containing the COMPLETE canonical contract.

No separately authored rules: AGENTS.md supplies every rule. --check never
writes; OSANWE_VAULT_ROOT supports isolated tests.
"""
import argparse
import hashlib
import os
from pathlib import Path

ROOT = Path(os.environ.get("OSANWE_VAULT_ROOT") or Path(__file__).resolve().parents[2])


def render(root=ROOT):
    contract = (root / "AGENTS.md").read_bytes()
    if not contract.strip():
        raise ValueError("AGENTS.md is empty")
    prefix = (
        "---\n"
        "aliases: [bootstrap]\n"
        "categories: [meta]\n"
        "type: reference\n"
        "status: active\n"
        "created: 2026-08-10\n"
        "updated: 2026-09-12\n"
        "tags: []\n"
        "related: []\n"
        "---\n\n"
        "<!-- GENERATED by .agents/scripts/gen-bootstrap.py; do not hand-edit.\n"
        "Standalone copy of the COMPLETE AGENTS.md contract follows.\n"
        "source-sha256: %s\n-->\n\n" % hashlib.sha256(contract).hexdigest()
    ).encode("ascii")
    return prefix + contract


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="compare only; never write")
    args = ap.parse_args()
    target = ROOT / "BOOTSTRAP.md"
    try:
        want = render()
        if args.check:
            if not target.is_file() or target.read_bytes() != want:
                print("gen-bootstrap --check FAIL: BOOTSTRAP.md differs from the complete AGENTS.md contract; run python .agents/scripts/gen-bootstrap.py")
                return 1
            print("gen-bootstrap --check OK: complete contract, byte-current")
        else:
            target.write_bytes(want)
            print("wrote BOOTSTRAP.md (%d bytes, complete canonical contract)" % len(want))
        return 0
    except (OSError, ValueError) as exc:
        print("gen-bootstrap FAIL: %s" % exc)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
