#!/usr/bin/env python3
"""gen-mcp-configs.py -- generate harness MCP configs from the registry of record.

Cross-harness migration D9 (plan of record, operator-approved 2026-08-10).
Registry: .agents/mcp/servers.json. DEFAULT-REFUSE semantics:
  - a server with write_surface=present is NEVER emitted into a harness config
    unless that harness's tool_filter is exactly "proven" (citation in registry);
    an "# OMITTED: no proven tool filter" stub is emitted instead.
  - scope=user servers are never emitted into committed project configs.
  - env tables carry variable NAMES/references only, never literal values
    (the EDGAR_IDENTITY name+email PII moved to the environment 2026-08-10).

Outputs (all carry a GENERATED header; hand-edits are drift):
  .mcp.json           Claude project scope -- read-only auth-free servers only
  opencode.json       OpenCode project config -- same trio
  .codex/config.toml  Codex project config -- same trio + preserved doc-budget header

Usage:
  python .agents/scripts/gen-mcp-configs.py          write all three
  python .agents/scripts/gen-mcp-configs.py --check  reconstruct + compare, exit 1 on drift
"""
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
REGISTRY = os.path.join(ROOT, ".agents", "mcp", "servers.json")

GEN_NOTE = ("GENERATED by .agents/scripts/gen-mcp-configs.py from .agents/mcp/servers.json "
            "-- do not hand-edit; edit the registry and re-run")


def load_registry():
    with io.open(REGISTRY, encoding="utf-8") as f:
        return json.load(f)["servers"]


def project_readonly(servers):
    out = {}
    for name, s in sorted(servers.items()):
        if s.get("scope") == "project" and s.get("write_surface") == "none":
            out[name] = s
    return out


def refused(servers):
    """Servers refused from project configs, with the reason for the stub comment."""
    out = []
    for name, s in sorted(servers.items()):
        if s.get("scope") != "project":
            out.append((name, "user-scope (never committed into clones)"))
        elif s.get("write_surface") == "present":
            out.append((name, "write-capable without a proven per-harness tool filter "
                              "(D9 default-refuse; omission is the control)"))
    return out


def gen_mcp_json(servers):
    body = {
        "_generated": GEN_NOTE,
        "_refused": ["%s: %s" % r for r in refused(servers)],
        "mcpServers": {},
    }
    for name, s in project_readonly(servers).items():
        entry = {"command": s["command"], "args": s.get("args", [])}
        env = {}
        for var in (s.get("env") or {}):
            env[var] = "${%s}" % var
        if env:
            entry["env"] = env
        body["mcpServers"][name] = entry
    return json.dumps(body, indent=2) + "\n"


def gen_opencode_json(servers):
    body = {
        "$schema": "https://opencode.ai/config.json",
        "mcp": {},
    }
    for name, s in project_readonly(servers).items():
        body["mcp"][name] = {
            "type": "local",
            "command": [s["command"]] + list(s.get("args", [])),
            "enabled": True,
        }
    return json.dumps(body, indent=2) + "\n"


def gen_codex_toml(servers):
    lines = [
        "# .codex/config.toml -- Codex CLI project config for Project Osanwe.",
        "# " + GEN_NOTE,
        "# verification: UNRUN (no non-Claude harness has executed this config yet;",
        "# marker cleared only by a committed conformance record -- publication honesty, S6).",
        "#",
        "# Loaded ONLY when the project is TRUSTED (run `codex` once here, accept the prompt).",
        "# Gates/write-discipline are honored BY INSTRUCTION from AGENTS.md (no [[hooks]]).",
        "",
        "# Concatenated AGENTS.md-chain headroom (default 32768; chain fits with room --",
        "# tools/router-check.py check 4 enforces against this configured budget).",
        "project_doc_max_bytes = 65536",
        "",
        "# ===== MCP servers (registry: .agents/mcp/servers.json) =====",
        "# Env vars are NAMES resolved from your environment -- no literals in this file.",
        "",
    ]
    for name, s in project_readonly(servers).items():
        lines.append("[mcp_servers.%s]" % name)
        lines.append('command = "%s"' % s["command"])
        if s.get("args"):
            lines.append("args = [%s]" % ", ".join('"%s"' % a for a in s["args"]))
        for var, note in (s.get("env") or {}).items():
            lines.append("# requires %s exported in your environment (%s)"
                         % (var, note.split("(")[0].strip().rstrip(";")))
        lines.append("")
    for name, why in refused(servers):
        lines.append("# OMITTED: %s -- %s" % (name, why))
        if name == "robinhood-trading":
            lines.append("#   Re-add ONLY after the enabled_tools live probe passes at S5 "
                         "(registry read-set == probe surface);")
            lines.append("#   the allowlist is then generated verbatim from the registry's "
                         "34-tool read set. See servers.json tool_filter.codex.")
    lines.append("")
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv[1:]
    servers = load_registry()
    targets = {
        os.path.join(ROOT, ".mcp.json"): gen_mcp_json(servers),
        os.path.join(ROOT, "opencode.json"): gen_opencode_json(servers),
        os.path.join(ROOT, ".codex", "config.toml"): gen_codex_toml(servers),
    }
    drift = []
    for path, want in targets.items():
        have = None
        if os.path.isfile(path):
            with io.open(path, encoding="utf-8", newline="") as f:
                have = f.read().replace("\r\n", "\n")
        if have == want:
            continue
        if check:
            drift.append(os.path.relpath(path, ROOT))
        else:
            with io.open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(want)
            print("wrote %s" % os.path.relpath(path, ROOT))
    if check:
        if drift:
            print("gen-mcp-configs --check FAIL: drift in %s (re-run the generator "
                  "or revert the hand-edit)" % ", ".join(drift))
            sys.exit(1)
        print("gen-mcp-configs --check OK: all generated configs current")
    sys.exit(0)


if __name__ == "__main__":
    main()
