#!/usr/bin/env python3
"""gen-roles.py -- OSANWE-V2 ADR-05: generate .claude/agents/*.md wrappers from
portable .agents/roles/<name>.md role files.

Contract mirrors sync.py discipline:
- canon = .agents/roles/<name>.md (frontmatter: name, description <=400 chars,
  tools, model, effort; body after '## Role Body' marker is the wrapper's body)
- derived = .claude/agents/<name>.md with GENERATED marker after frontmatter
- a role file with NO frontmatter is a relay worker system prompt (tools/relay.py
  and config/local-lane.json load those BY PATH, byte-identically), not an agent
  definition: no wrapper is emitted for it, and a wrapper a previous run
  generated for it is removed -- an agent file with no name/description/tools has
  nothing for the harness to register
- --check reconstruct-and-compare, write nothing, exit 1 on drift
- hand-authored derived files WITHOUT the generated marker are never touched

One-shot migration aid: --absorb <derived-name> seeds a NEW role file from an
existing .claude/agents definition (frontmatter slimmed to <=400-char
description; full original description preserved in the body), so the 14
existing agents can be adopted without losing any wording.
"""

import os
import re
import sys

import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ROLES = os.path.join(ROOT, ".agents", "roles")
AGENTS = os.path.join(ROOT, ".claude", "agents")
AGENTS_BACKUP = os.path.join(ROOT, "_archive", "2026-08-overhaul", "agents-pre-gen-roles")
MARKER_NAME = ".agents/scripts/gen-roles.py"
MAX_DESC = 400


def generated_marker(name):
    return ("<!-- GENERATED by %s from .agents/roles/%s.md -- "
            "DO NOT EDIT (edit the role file, re-run gen-roles) -->" % (MARKER_NAME, name))


def read_lf(p):
    with open(p, "r", encoding="utf-8", newline="") as f:
        return f.read().replace("\r\n", "\n").replace("\r", "\n")


def parse_fm(text):
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 4)
    if end < 0:
        return {}, text
    fm_raw = text[4:end]
    body = text[end + 5:]
    fm = {}
    for line in fm_raw.splitlines():
        m = re.match(r"^([A-Za-z_-]+):\s*(.*)$", line)
        if m:
            fm[m.group(1)] = m.group(2).strip()
    return fm, body


def build_wrapper(role_path):
    text = read_lf(role_path)
    fm, body = parse_fm(text)
    if "## Role Body" in body:
        body = body.split("## Role Body", 1)[1].lstrip("\n")
    name = fm.get("name") or os.path.splitext(os.path.basename(role_path))[0]
    lines = ["---"]
    for k in ("name", "description", "tools", "model", "effort", "color"):
        if k in fm:
            lines.append(f"{k}: {fm[k]}")
    lines += ["---", generated_marker(name), "", body.rstrip() + "\n"]
    return "\n".join(lines)


def role_files():
    if not os.path.isdir(ROLES):
        return []
    return [os.path.join(ROLES, f) for f in sorted(os.listdir(ROLES))
            if f.endswith(".md") and not f.startswith("_")]


def main():
    check = "--check" in sys.argv
    absorb = None
    if "--absorb" in sys.argv:
        absorb = sys.argv[sys.argv.index("--absorb") + 1]

    if absorb:
        src = os.path.join(AGENTS, absorb + ".md")
        text = read_lf(src)
        fm, body = parse_fm(text)
        desc = fm.get("description", "")
        short = desc[: MAX_DESC - 3].rstrip() + "..." if len(desc) > MAX_DESC else desc
        role_body = ("# " + absorb + "\n\n"
                     "<!-- ORIGINAL DESCRIPTION (verbatim, superseded frontmatter) -->\n"
                     + desc + "\n\n" + body.strip() + "\n")
        out = ["---", f"name: {absorb}",
               'description: "%s"' % short.replace('"', "'")]
        for k in ("tools", "model", "effort", "color"):
            if k in fm:
                out.append(f"{k}: {fm[k]}")
        out += ["---", "", "## Role Body", "", role_body]
        dst = os.path.join(ROLES, absorb + ".md")
        with open(dst, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(out))
        print(f"absorbed {absorb} -> {dst} ({len(short)} char description)")
        return 0

    problems, actions = [], []
    existing_derived = {}
    if os.path.isdir(AGENTS):
        for f in sorted(os.listdir(AGENTS)):
            if f.endswith(".md"):
                p = os.path.join(AGENTS, f)
                existing_derived[f] = read_lf(p)

    for rp in role_files():
        name = os.path.splitext(os.path.basename(rp))[0]
        want_name = name + ".md"
        cur = existing_derived.get(want_name)
        if not parse_fm(read_lf(rp))[0]:
            # relay-only role prompt: nothing to register, so emit nothing and
            # clear away any wrapper an earlier run generated for it
            if cur is not None and generated_marker(name) in cur[:600]:
                if check:
                    problems.append(f"{want_name}: generated wrapper for a "
                                    "frontmatter-less relay role file "
                                    "(run without --check to remove)")
                else:
                    os.remove(os.path.join(AGENTS, want_name))
                    actions.append(f"removed {want_name} "
                                   "(relay-only role file, not an agent definition)")
            continue
        want = build_wrapper(rp)
        if cur == want:
            continue
        if cur is not None and generated_marker(name) not in cur[:600]:
            # pre-existing hand-authored definition: preserve verbatim to the
            # archive (HB-03 archive-not-delete), then generate the wrapper
            if not check:
                os.makedirs(AGENTS_BACKUP, exist_ok=True)
                bkp = os.path.join(AGENTS_BACKUP, want_name)
                if not os.path.exists(bkp):
                    shutil.copyfile(os.path.join(AGENTS, want_name), bkp)
                    actions.append(f"archived prior {want_name}")
            elif "--no-backup" not in sys.argv:
                problems.append(f"{want_name}: pre-existing definition would be "
                                "superseded (run without --check to archive+generate)")
                continue
        if check:
            problems.append(f"{want_name}: drifts from role file")
            continue
        os.makedirs(AGENTS, exist_ok=True)
        with open(os.path.join(AGENTS, want_name), "w", encoding="utf-8", newline="\n") as f:
            f.write(want)
        actions.append(f"wrote {want_name}")

    if check:
        if problems:
            print("gen-roles --check FAIL:")
            for p in problems:
                print("  " + p)
            return 1
        print("gen-roles --check OK (%d role files)" % len(role_files()))
        return 0

    for a in actions:
        print(a)
    print("gen-roles: %d action(s) over %d role file(s)" % (len(actions), len(role_files())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
