#!/usr/bin/env python3
"""sync.py -- Branch G derived-copy generator: canon .agents/skills/ -> derived .claude/skills/.

Cross-harness migration D3 (plan of record, operator-approved 2026-08-10).
Canon lives at .agents/skills/<name>/ (native for Codex/OpenCode/Goose/Crush/Cline/Pi).
Claude Code reads the DERIVED committed copies at .claude/skills/<name>/.

Contract (red-team-hardened):
- Per-file allowlist: SKILL.md (transformed), ref-*.md (skill-dir top level),
  scripts/** and assets/** (copied; text LF-normalized).
- NEVER-TOUCH list: .claude/skills/_archive/ and .claude/skills/AGENTS.md (and a
  CLAUDE.md, should one reappear) -- sync neither writes nor deletes these, ever.
- UNMIGRATED GUARD: a canon SKILL.md still carrying the legacy pointer-adapter
  marker ("CODEX ADAPTER (generated by ...") is NOT canon content -- it is the
  retired generator's stub awaiting its S3 batch. sync SKIPS it entirely; the
  live .claude/skills/<name>/ stays canonical for that skill until migrated.
- GENERATED marker goes IMMEDIATELY after the closing frontmatter fence
  (derived byte 0 stays '---'; driftcheck asserts both).
- allowed-tools re-materialized top-level in derived from canon
  metadata."osanwe-allowed-tools" (space-separated string -> YAML list).
  Canon itself carries NO top-level allowed-tools (validate enforces) -- so
  there is no Tier-A privilege widening surface: derived == canon metadata set.
- Orphan deletion: a derived dir whose SKILL.md carries OUR generated marker
  and whose canon source is gone is deleted (file-level orphans inside a
  migrated skill are deleted too). Hand-authored derived dirs are never deleted.
- LF enforced everywhere (.gitattributes pins eol=lf -- named dependency).

Usage:
  python .agents/scripts/sync.py            apply (writes derived copies)
  python .agents/scripts/sync.py --check    reconstruct-and-compare, write nothing;
                                            exit 1 on any difference
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CANON = os.path.join(ROOT, ".agents", "skills")
DERIVED = os.path.join(ROOT, ".claude", "skills")

LEGACY_ADAPTER_MARKER = "CODEX ADAPTER (generated by tools/gen-codex-skill-adapters.py"
NEVER_TOUCH_DIRS = {"_archive"}
NEVER_TOUCH_FILES = {"AGENTS.md", "CLAUDE.md"}
TEXT_EXT = {".md", ".py", ".sh", ".json", ".yaml", ".yml", ".toml", ".txt", ".base"}


def generated_marker(name):
    return ("<!-- GENERATED by .agents/scripts/sync.py from .agents/skills/%s/ -- "
            "DO NOT EDIT (edit canon, re-run sync) -->" % name)


def is_text(path):
    return os.path.splitext(path)[1].lower() in TEXT_EXT


def read_lf(path):
    with io.open(path, "r", encoding="utf-8", newline="") as f:
        return f.read().replace("\r\n", "\n").replace("\r", "\n")


def read_bytes(path):
    with open(path, "rb") as f:
        return f.read()


def split_frontmatter(text):
    """Return (fm_body_text, rest_after_closing_fence_line) or None."""
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 3)
    if end < 0:
        # closing fence at EOF
        if text.endswith("\n---"):
            return text[4:-3], ""
        return None
    return text[4:end + 1], text[end + len("\n---\n"):]


def parse_meta_allowed_tools(fm_text):
    """Line-based pull of metadata.osanwe-allowed-tools (quoted or plain scalar)."""
    in_meta = False
    for line in fm_text.split("\n"):
        if line.startswith("metadata:"):
            in_meta = True
            continue
        if in_meta:
            if line[:1] not in (" ", "\t") and line.strip():
                in_meta = False
                continue
            s = line.strip()
            if s.startswith("osanwe-allowed-tools:"):
                v = s[len("osanwe-allowed-tools:"):].strip()
                if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
                    v = v[1:-1]
                return [t for t in v.split() if t]
    return None


def transform_skill_md(name, canon_text):
    """Canonical -> derived SKILL.md transform. Deterministic; shared by driftcheck."""
    parts = split_frontmatter(canon_text)
    if parts is None:
        raise ValueError("canon SKILL.md for %s has no parseable frontmatter fence" % name)
    fm, body = parts
    tools = parse_meta_allowed_tools(fm)
    fm_out = fm
    if tools:
        if not fm_out.endswith("\n"):
            fm_out += "\n"
        fm_out += "allowed-tools: [%s]\n" % ", ".join(tools)
    return "---\n" + fm_out + "---\n" + generated_marker(name) + "\n" + body


def migrated_canon_skills():
    """Canon skill dirs whose SKILL.md is real content (not a legacy adapter stub)."""
    out = []
    if not os.path.isdir(CANON):
        return out
    for name in sorted(os.listdir(CANON)):
        if name in NEVER_TOUCH_DIRS or name in NEVER_TOUCH_FILES:
            continue  # redteam N5: never-touch enforced on the WRITE path too --
            # a crafted canon _archive/ dir must not clobber the derived archive
        d = os.path.join(CANON, name)
        smd = os.path.join(d, "SKILL.md")
        if not os.path.isdir(d) or not os.path.isfile(smd):
            continue
        if LEGACY_ADAPTER_MARKER in read_lf(smd):
            # Post-cutover (M1 flip 2026-08-10): no legitimate stubs exist.
            # A legacy adapter marker in canon means a corrupted or reverted
            # canon file -- refuse to sync anything rather than silently skip.
            raise SystemExit(
                "sync: FATAL -- legacy CODEX ADAPTER marker found in canon skill '%s'. "
                "All 15 skills migrated at the 2026-08-10 cutover; a stub in canon is "
                "corruption or an accidental revert. Restore the real SKILL.md from git "
                "history before syncing." % name)
        out.append(name)
    return out


def canon_file_set(name):
    """Allowlisted relative paths for one canon skill."""
    d = os.path.join(CANON, name)
    rels = []
    for fn in sorted(os.listdir(d)):
        p = os.path.join(d, fn)
        if os.path.isfile(p) and (fn == "SKILL.md" or (fn.startswith("ref-") and fn.endswith(".md"))):
            rels.append(fn)
    for sub in ("scripts", "assets"):
        base = os.path.join(d, sub)
        if os.path.isdir(base):
            for root, _dirs, files in os.walk(base):
                for fn in sorted(files):
                    rels.append(os.path.relpath(os.path.join(root, fn), d).replace("\\", "/"))
    return rels


def expected_derived_bytes(name, rel):
    src = os.path.join(CANON, name, rel.replace("/", os.sep))
    if rel == "SKILL.md":
        return transform_skill_md(name, read_lf(src)).encode("utf-8")
    if is_text(src):
        return read_lf(src).encode("utf-8")
    return read_bytes(src)


def actual_derived_bytes(name, rel):
    p = os.path.join(DERIVED, name, rel.replace("/", os.sep))
    if not os.path.isfile(p):
        return None
    if is_text(p):
        return read_lf(p).encode("utf-8")
    return read_bytes(p)


def derived_orphan_dirs():
    """Derived dirs carrying OUR generated marker with no canon source."""
    out = []
    if not os.path.isdir(DERIVED):
        return out
    for name in sorted(os.listdir(DERIVED)):
        if name in NEVER_TOUCH_DIRS:
            continue
        d = os.path.join(DERIVED, name)
        smd = os.path.join(d, "SKILL.md")
        if not os.path.isdir(d) or not os.path.isfile(smd):
            continue
        text = read_lf(smd)
        if "<!-- GENERATED by .agents/scripts/sync.py" in text and \
                not os.path.isdir(os.path.join(CANON, name)):
            out.append(name)
    return out


def sync(check=False):
    problems, actions = [], []
    for name in migrated_canon_skills():
        rels = canon_file_set(name)
        ddir = os.path.join(DERIVED, name)
        for rel in rels:
            want = expected_derived_bytes(name, rel)
            have = actual_derived_bytes(name, rel)
            if have == want:
                continue
            if check:
                problems.append("%s/%s: %s" % (name, rel,
                                "missing in derived" if have is None else "bytes differ"))
            else:
                dst = os.path.join(ddir, rel.replace("/", os.sep))
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                with open(dst, "wb") as f:
                    f.write(want)
                actions.append("wrote %s/%s" % (name, rel))
        # file-level orphans inside a migrated derived dir
        if os.path.isdir(ddir):
            want_set = set(rels)
            for root, _dirs, files in os.walk(ddir):
                for fn in files:
                    rel = os.path.relpath(os.path.join(root, fn), ddir).replace("\\", "/")
                    if rel not in want_set:
                        if check:
                            problems.append("%s/%s: derived file has no canon source" % (name, rel))
                        else:
                            os.remove(os.path.join(root, fn))
                            actions.append("removed orphan %s/%s" % (name, rel))
    for name in derived_orphan_dirs():
        if check:
            problems.append("%s/: generated derived dir, canon source gone (orphan dir)" % name)
        else:
            import shutil
            shutil.rmtree(os.path.join(DERIVED, name))
            actions.append("removed orphan dir %s/" % name)
    return problems, actions


def main():
    check = "--check" in sys.argv[1:]
    migrated = migrated_canon_skills()
    problems, actions = sync(check=check)
    if check:
        if problems:
            print("sync --check FAIL (%d difference(s); %d migrated skill(s) checked):"
                  % (len(problems), len(migrated)))
            for p in problems:
                print("  - " + p)
            sys.exit(1)
        print("sync --check OK: %d migrated skill(s), derived tree matches canon" % len(migrated))
        sys.exit(0)
    for a in actions:
        print("  " + a)
    print("sync: %d migrated skill(s), %d action(s)" % (len(migrated), len(actions)))
    sys.exit(0)


if __name__ == "__main__":
    main()
