#!/usr/bin/env python3
"""validate.py -- spec + policy validation for the canon skills tree and generated configs.

Cross-harness migration D7/D9 (plan of record, operator-approved 2026-08-10).

Skill checks (canon .agents/skills/<name>/, migrated skills only -- a SKILL.md still
carrying the legacy "CODEX ADAPTER" marker is unmigrated and reported, not validated):
  - strict YAML frontmatter parse (quoted scalars; the harness is lenient, the toolchain is not)
  - spec top-level fields ONLY: name, description, metadata (+ optional license, version).
    Top-level allowed-tools is REJECTED in canon (it is re-materialized in the Claude
    derived copy by sync.py from metadata.osanwe-allowed-tools -- single source, no
    Tier-A privilege widening).
  - name: 1-64 chars, lowercase-hyphen, no '--', == directory name
  - description: required, non-empty, <= 500 chars (Osanwe D7 hard cap; spec allows 1024),
    trigger keyword in the first 200 chars (WARN), ASCII
  - metadata: string -> string map
  - ASCII bytes in SKILL.md and every ref-*.md (Pattern 22)
  - "Distinct from" disambiguation survival: decide<->challenge, enrich<->ingest,
    spark<->consolidate descriptions must each name their confusion sibling
  - health description compound-free (D7 content-hygiene reinterpretation,
    ratified in the 2026-08-10 /decide record): pinned blocklist
  - listing budget: entry = len(name)+4+min(len(desc),1536); canon tree target
    sum <= 8000 => budget_mode fits (enforced as FAIL only when all 15 are migrated)

Config checks (guarded on existence; grow at S2.5):
  - .agents/mcp/servers.json parses; env vars are NAMES only (no literal secrets:
    reject '@'-containing or path-like literal values in env tables)
  - generated harness configs (.codex/config.toml, opencode.json, .mcp.json):
    no backslash paths, no MSYS /c/ paths, no literal email/PII in env values
  - positive set-equality: Codex enabled_tools == registry read-set for each server
  - inverse: every write_surface=present server absent-or-filtered in every config

Exit 0 = no FAIL. --json for machine consumption.
"""
import io
import json
import os
import re
import sys

try:
    import yaml
except ImportError:
    yaml = None

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CANON = os.path.join(ROOT, ".agents", "skills")
REGISTRY = os.path.join(ROOT, ".agents", "mcp", "servers.json")
LEGACY_ADAPTER_MARKER = "CODEX ADAPTER (generated by tools/gen-codex-skill-adapters.py"

SPEC_ALLOWED_TOP = {"name", "description", "metadata", "license", "version"}
SPEC_NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
DESC_HARD_CAP = 500
LISTING_DESC_CAP = 1536   # binary-verified skillListingMaxDescChars
LISTING_BUDGET = 8000     # binary-verified 1% of 200k ctx
EXPECTED_SKILL_COUNT = 16
TRIGGER_CUES = ("use when", "use ", "when ", "before ", "after ", "whenever", "trigger")

DISTINCT_PAIRS = {  # confusion siblings whose disambiguation must survive compression
    "decide": "challenge", "challenge": "decide",
    "enrich": "ingest", "ingest": "enrich",
    "spark": "consolidate", "consolidate": "spark",
}
# D7: health canon description must be compound-free (body/refs unchanged).
HEALTH_DESC_BLOCKLIST = (
    "<compound-1>", "<compound-2>", "<compound-3>", "<compound-4>", "<compound-5>",
    "<compound-6>", "<compound-7>", "<compound-8>", "<compound-9>", "<compound-10>",
    "<compound-11>", "<compound-12>", "<compound-13>",
)


def read_lf(path):
    with io.open(path, "r", encoding="utf-8", newline="") as f:
        return f.read().replace("\r\n", "\n").replace("\r", "\n")


def ascii_offenders(path):
    with open(path, "rb") as f:
        raw = f.read()
    return [i for i, b in enumerate(raw) if b > 127][:3]


def split_frontmatter(text):
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 3)
    if end < 0:
        return None
    return text[4:end + 1], text[end + 5:]


def validate_skills(fails, warns, info):
    migrated, unmigrated = [], []
    if not os.path.isdir(CANON):
        fails.append(("skills", "canon tree .agents/skills/ missing"))
        return migrated, unmigrated
    for name in sorted(os.listdir(CANON)):
        d = os.path.join(CANON, name)
        smd = os.path.join(d, "SKILL.md")
        if not os.path.isdir(d) or not os.path.isfile(smd):
            continue
        text = read_lf(smd)
        if LEGACY_ADAPTER_MARKER in text:
            # Post-cutover (M1 flip 2026-08-10): stubs are corruption, not pending work.
            fails.append(("skills", "%s: legacy CODEX ADAPTER marker in CANON SKILL.md "
                          "-- no legitimate stubs exist post-cutover; restore from git "
                          "history" % name))
            unmigrated.append(name)
            continue
        migrated.append(name)
        # ASCII (SKILL.md + refs)
        for fn in [smd] + [os.path.join(d, f) for f in sorted(os.listdir(d))
                           if f.startswith("ref-") and f.endswith(".md")]:
            off = ascii_offenders(fn)
            if off:
                fails.append(("skills", "%s: non-ASCII byte(s) at offsets %s (Pattern 22)"
                              % (os.path.relpath(fn, ROOT), off)))
        parts = split_frontmatter(text)
        if parts is None:
            fails.append(("skills", "%s: no frontmatter fence" % name))
            continue
        fm_text, _body = parts
        if yaml is None:
            warns.append(("skills", "PyYAML unavailable; strict-parse checks skipped"))
            continue
        try:
            fm = yaml.safe_load(fm_text)
        except yaml.YAMLError as exc:
            fails.append(("skills", "%s: frontmatter fails strict YAML: %s" % (name, str(exc)[:100])))
            continue
        if not isinstance(fm, dict):
            fails.append(("skills", "%s: frontmatter not a mapping" % name))
            continue
        extra = sorted(set(fm) - SPEC_ALLOWED_TOP)
        if extra:
            fails.append(("skills", "%s: non-spec top-level keys %s (Osanwe fields ride "
                          "stringified in metadata; allowed-tools lives ONLY in "
                          "metadata.osanwe-allowed-tools)" % (name, extra)))
        nm = str(fm.get("name", ""))
        if nm != name:
            fails.append(("skills", "%s: frontmatter name %r != dirname" % (name, nm)))
        if not (1 <= len(nm) <= 64) or not SPEC_NAME_RE.match(nm):
            fails.append(("skills", "%s: name violates spec (1-64, lowercase-hyphen, no '--')" % name))
        desc = str(fm.get("description", "") or "")
        if not desc:
            fails.append(("skills", "%s: description missing/empty" % name))
        if len(desc) > DESC_HARD_CAP:
            fails.append(("skills", "%s: description %d chars > %d hard cap (D7)"
                          % (name, len(desc), DESC_HARD_CAP)))
        if desc and not any(c in desc[:200].lower() for c in TRIGGER_CUES):
            warns.append(("skills", "%s: no trigger cue in first 200 chars of description" % name))
        meta = fm.get("metadata")
        if not isinstance(meta, dict):
            fails.append(("skills", "%s: metadata mapping missing (spec string->string)" % name))
        else:
            bad = [k for k, v in meta.items()
                   if not isinstance(k, str) or not isinstance(v, str)]
            if bad:
                fails.append(("skills", "%s: metadata non-string entries %s" % (name, bad)))
        sib = DISTINCT_PAIRS.get(name)
        if sib and desc and sib not in desc.lower():
            fails.append(("skills", "%s: description lost its disambiguation vs '%s' "
                          "(D7: Distinct-from substance must survive compression)" % (name, sib)))
        if name == "health" and desc:
            hits = [w for w in HEALTH_DESC_BLOCKLIST if w in desc.lower()]
            if hits:
                fails.append(("skills", "health: description carries compound name(s) %s "
                              "(D7 content-hygiene: canon description is compound-free)" % hits))
    return migrated, unmigrated


def listing_budget(fails, warns, info, migrated, unmigrated):
    """Compute over the EFFECTIVE Claude listing (derived tree = what Claude reads)."""
    derived = os.path.join(ROOT, ".claude", "skills")
    entries = {}
    for name in sorted(os.listdir(derived)) if os.path.isdir(derived) else []:
        smd = os.path.join(derived, name, "SKILL.md")
        if name.startswith("_") or not os.path.isfile(smd):
            continue
        text = read_lf(smd)
        parts = split_frontmatter(text)
        desc = ""
        if parts and yaml is not None:
            try:
                fm = yaml.safe_load(parts[0])
                if isinstance(fm, dict):
                    desc = str(fm.get("description", "") or "")
            except yaml.YAMLError:
                m = re.search(r"^description:\s*(.+)$", parts[0], re.M)
                desc = m.group(1) if m else ""
        entries[name] = len(name) + 4 + min(len(desc), LISTING_DESC_CAP)
    total = sum(entries.values())
    mode = "fits" if total <= LISTING_BUDGET else "priority"
    info.append(("budget", "effective Claude listing: %d skills, %d chars vs %d budget -> %s"
                 % (len(entries), total, LISTING_BUDGET, mode)))
    if len(migrated) >= EXPECTED_SKILL_COUNT and mode != "fits":
        fails.append(("budget", "all %d skills migrated but listing still %d > %d "
                      "(DoD 3 requires budget_mode=fits)" % (EXPECTED_SKILL_COUNT, total, LISTING_BUDGET)))
    elif mode != "fits":
        warns.append(("budget", "listing over budget (expected pre-migration: %d/%d skills migrated)"
                      % (len(migrated), EXPECTED_SKILL_COUNT)))
    return {"entries": entries, "total": total, "mode": mode}


def _env_value_suspicious(v):
    v = str(v)
    return ("@" in v) or re.search(r"[A-Za-z]:\\\\|/c/", v) is not None


def validate_configs(fails, warns, info):
    reg = None
    if os.path.isfile(REGISTRY):
        try:
            reg = json.loads(read_lf(REGISTRY))
        except Exception as exc:
            fails.append(("mcp", "servers.json unparseable: %r" % exc))
    else:
        info.append(("mcp", "registry .agents/mcp/servers.json not present yet (pre-S2.5)"))
        return
    servers = reg.get("servers", {})
    # Redteam H2: write_surface must be INTERNALLY CONSISTENT -- a server with
    # declared write_tools (or a tool_filter) cannot claim write_surface=none,
    # else a two-field registry edit would emit it into every config with all
    # checkers green. Known write-capable servers are additionally pinned by name.
    KNOWN_WRITE_CAPABLE = {"robinhood-trading", "claudewatch"}
    for sname, s in servers.items():
        if s.get("write_surface") != "present":
            if s.get("write_tools") or s.get("tool_filter"):
                fails.append(("mcp", "%s: declares write_tools/tool_filter but "
                              "write_surface != present (H2 self-attestation guard)" % sname))
            if sname in KNOWN_WRITE_CAPABLE:
                fails.append(("mcp", "%s: name-pinned write-capable but registry claims "
                              "write_surface=%r (H2)" % (sname, s.get("write_surface"))))
        for k, v in (s.get("env") or {}).items():
            if _env_value_suspicious(v):
                fails.append(("mcp", "%s: env %s carries a literal value (%r); registry "
                              "records env-var NAMES only (D9)" % (sname, k, str(v)[:40])))
    # Codex config: enabled_tools set-equality + write-capable omission
    codex_cfg = os.path.join(ROOT, ".codex", "config.toml")
    if os.path.isfile(codex_cfg):
        text = read_lf(codex_cfg)
        if re.search(r"[A-Za-z]:\\\\", text) or re.search(r'"/c/', text):
            fails.append(("codex", "backslash or MSYS /c/ path in .codex/config.toml"))
        if re.search(r"@\w+\.(com|net|org|io)", text):
            fails.append(("codex", "literal email/PII in .codex/config.toml (D9: move to environment)"))
        for sname, s in servers.items():
            if s.get("write_surface") == "present":
                m = re.search(r"\[mcp_servers\.%s\]" % re.escape(sname), text)
                if m:
                    filt = s.get("tool_filter", {}).get("codex")
                    if filt != "proven":
                        fails.append(("codex", "%s: write-capable server emitted into Codex config "
                                      "without a PROVEN tool filter (D9 default-refuse)" % sname))
                    else:
                        seg = text[m.end():]
                        nxt = seg.find("[mcp_servers.")
                        seg = seg[:nxt] if nxt > 0 else seg
                        em = re.search(r"enabled_tools\s*=\s*\[([^\]]*)\]", seg)
                        if not em:
                            fails.append(("codex", "%s: write-capable, proven filter claimed, but no "
                                          "enabled_tools allowlist in config" % sname))
                        else:
                            cfg_set = set(re.findall(r'"([^"]+)"', em.group(1)))
                            reg_set = set(s.get("read_tools", []))
                            if cfg_set != reg_set:
                                fails.append(("codex", "%s: enabled_tools != registry read-set "
                                              "(only-config=%s only-registry=%s)"
                                              % (sname, sorted(cfg_set - reg_set)[:5],
                                                 sorted(reg_set - cfg_set)[:5])))
    # opencode.json: same inverse sweep (redteam M6 -- the docstring promised
    # "every config"; now the code delivers it)
    oc_json = os.path.join(ROOT, "opencode.json")
    if os.path.isfile(oc_json):
        try:
            oc = json.loads(read_lf(oc_json))
        except Exception as exc:
            fails.append(("opencode", "opencode.json unparseable: %r" % exc))
            oc = {}
        for sname in (oc.get("mcp") or {}):
            s = servers.get(sname)
            if s is None:
                fails.append(("opencode", "opencode.json server %r not in registry" % sname))
            elif s.get("write_surface") == "present":
                fails.append(("opencode", "opencode.json carries write-capable server %r "
                              "(default-refuse: omission is the control)" % sname))
            elif s.get("scope") != "project":
                fails.append(("opencode", "opencode.json server %r registry scope is %r, "
                              "not 'project'" % (sname, s.get("scope"))))
    # .mcp.json: committed project scope = read-only auth-free only
    mcp_json = os.path.join(ROOT, ".mcp.json")
    if os.path.isfile(mcp_json):
        try:
            mj = json.loads(read_lf(mcp_json))
        except Exception as exc:
            fails.append(("mcp", ".mcp.json unparseable: %r" % exc))
            mj = {}
        for sname in (mj.get("mcpServers") or {}):
            s = servers.get(sname)
            if s is None:
                fails.append(("mcp", ".mcp.json server %r not in registry" % sname))
            elif s.get("write_surface") == "present":
                fails.append(("mcp", ".mcp.json carries write-capable server %r (D9: committed "
                              "project scope is read-only auth-free only)" % sname))
            elif s.get("scope") != "project":
                fails.append(("mcp", ".mcp.json server %r registry scope is %r, not 'project'"
                              % (sname, s.get("scope"))))


def main():
    as_json = "--json" in sys.argv[1:]
    fails, warns, info = [], [], []
    migrated, unmigrated = validate_skills(fails, warns, info)
    budget = listing_budget(fails, warns, info, migrated, unmigrated)
    validate_configs(fails, warns, info)
    result = {
        "migrated": migrated, "unmigrated": unmigrated, "budget": budget,
        "fails": ["[%s] %s" % f for f in fails],
        "warns": ["[%s] %s" % w for w in warns],
        "info": ["[%s] %s" % i for i in info],
    }
    if as_json:
        print(json.dumps(result, indent=1))
    else:
        print("validate -- canon skills + configs (%s)" % ROOT)
        print("  migrated: %d %s" % (len(migrated), migrated))
        print("  stub-marker FAILs (must be 0 post-cutover): %d" % len(unmigrated))
        for level, rows in (("FAIL", fails), ("WARN", warns), ("INFO", info)):
            for area, msg in rows:
                print("  [%s/%s] %s" % (level, area, msg))
        print("result: %d FAIL / %d WARN" % (len(fails), len(warns)))
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
