#!/usr/bin/env python3
"""calibration-report.py -- factor-level error taxonomy over graded predictions.

Consumes the JSONL from backtest-prediction.py and produces a markdown report:
  1. Headline calibration: accuracy overall / by confidence band / by direction.
  2. Confidence calibration: does stated confidence track realized accuracy?
     (bins of 10; the SOTA question is whether 80% calls win ~80% of the time)
  3. Factor attribution: for WRONG predictions, which evidence buckets dominated
     the as-of reasoning vs for RIGHT ones -- where does the calculation go wrong.
  4. Per-ticker and per-era stability.
Output: wiki/maintenance/calibration/calibration-<date>.md (+ json beside).
"""

import argparse
import json
import sys
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def load(jsonl):
    rows = []
    with open(jsonl, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def pct(n, d):
    return f"{n/d:.0%}" if d else "--"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--jsonl", default="Efforts/osanwe-v2-overhaul/_work/calibration-21d.jsonl")
    ap.add_argument("--horizon", type=int, default=21)
    args = ap.parse_args()

    rows = load(ROOT / args.jsonl if not Path(args.jsonl).is_absolute() else args.jsonl)
    if not rows:
        print("no records; run backtest-prediction.py --run first")
        return 2
    n = len(rows)
    correct = [r for r in rows if r["correct"]]
    wrong = [r for r in rows if not r["correct"]]

    out = []
    add = out.append
    add("---")
    add("aliases: []")
    add("categories: [wiki]")
    add("type: report")
    add("status: active")
    add(f"created: {date.today().isoformat()}")
    add(f"updated: {date.today().isoformat()}")
    add("tags: [topic/meta]")
    add('related: ["[[score-ledger]]"]')
    add("---")
    add("")
    add(f"# Retrospective calibration report ({args.horizon}d horizon)")
    add("")
    add(f"GENERATED by tools/calibration-report.py from {n} point-in-time graded "
        f"predictions ({rows[0]['t0']} .. {rows[-1]['t0']}). Zero lookahead: analysis "
        "text from git at commit date; prices strictly post-date.")
    add("")

    # 1 headline
    add("## 1. Direction accuracy")
    add("")
    add(f"- Overall: **{pct(len(correct), n)}** ({len(correct)}/{n}) at +/-2pct threshold")
    bull = [r for r in rows if r["direction_wanted"] == "up"]
    bear = [r for r in rows if r["direction_wanted"] == "down"]
    flat = [r for r in rows if r["direction_wanted"] == "flat"]
    add(f"- Bullish calls: {pct(sum(1 for r in bull if r['correct']), len(bull))} ({len(bull)})")
    add(f"- Bearish calls: {pct(sum(1 for r in bear if r['correct']), len(bear))} ({len(bear)})")
    if flat:
        add(f"- Flat calls: {pct(sum(1 for r in flat if r['correct']), len(flat))} ({len(flat)})")

    # 2 confidence calibration
    add("")
    add("## 2. Confidence calibration (does 80% confidence mean ~80% right?)")
    add("")
    add("| stated confidence | n | realized accuracy | gap |")
    add("|---|---|---|---|")
    bins = defaultdict(list)
    for r in rows:
        c = r.get("confidence")
        if c is None:
            continue
        bins[min(c // 10 * 10, 90)].append(r)
    for b in sorted(bins):
        rs = bins[b]
        acc = sum(1 for r in rs if r["correct"]) / len(rs)
        stated = (b + 5) / 100
        gap = acc - stated
        add(f"| {b}-{b+9} | {len(rs)} | {acc:.0%} | {gap:+.0%} |")
    add("")

    # 3 factor attribution on errors
    add("## 3. Where the calculation goes wrong (factor attribution)")
    add("")
    add("Mean factor weight in AS-OF reasoning, right vs wrong calls:")
    add("")
    keys = sorted(rows[0]["factors"].keys())
    add("| factor | right calls | wrong calls | delta |")
    add("|---|---|---|---|")
    for k in keys:
        rw = sum(r["factors"].get(k, 0) for r in correct) / max(len(correct), 1)
        ww = sum(r["factors"].get(k, 0) for r in wrong) / max(len(wrong), 1)
        add(f"| {k} | {rw:.3f} | {ww:.3f} | {ww-rw:+.3f} |")
    add("")
    add("Reading: a POSITIVE delta means the factor was weighted MORE heavily in calls"
        " that turned out wrong -- the leading suspect for miscalibration.")

    # biggest misses
    add("")
    add("## 4. Largest misses (magnitude-ranked)")
    add("")
    ranked = sorted(wrong, key=lambda r: abs(r["fwd_ret_pct"]), reverse=True)[:8]
    add("| id | verdict | conf | wanted | fwd ret | miss |")
    add("|---|---|---|---|---|---|")
    for r in ranked:
        add(f"| {r['id']} | {r['verdict']} | {r.get('confidence') or '--'} | "
            f"{r['direction_wanted']} | {r['fwd_ret_pct']:+.1f}% | "
            f"{abs(r['fwd_ret_pct']):.1f}% |")
    add("")

    # per ticker
    add("## 5. Per-ticker stability")
    add("")
    by_ticker = defaultdict(list)
    for r in rows:
        by_ticker[r["ticker"]].append(r)
    add("| ticker | n | accuracy | avg fwd ret |")
    add("|---|---|---|---|")
    for t in sorted(by_ticker, key=lambda t: -len(by_ticker[t]))[:12]:
        rs = by_ticker[t]
        acc = sum(1 for r in rs if r["correct"]) / len(rs)
        avg = sum(r["fwd_ret_pct"] for r in rs) / len(rs)
        add(f"| {t} | {len(rs)} | {acc:.0%} | {avg:+.1f}% |")

    text = "\n".join(out) + "\n"

    outdir = ROOT / "wiki" / "maintenance" / "calibration"
    outdir.mkdir(parents=True, exist_ok=True)
    md = outdir / f"calibration-{date.today().isoformat()}.md"
    md.write_text(text, encoding="utf-8", newline="\n")
    (outdir / f"calibration-{date.today().isoformat()}.json").write_text(
        json.dumps(rows, indent=1), encoding="utf-8", newline="\n")
    print(f"report -> {md.relative_to(ROOT)} ({len(text)} bytes); json beside it")
    return 0


if __name__ == "__main__":
    sys.exit(main())
