#!/usr/bin/env python3
"""confidence-calibrator.py -- turn measured miscalibration into a correction.

Consumes calibration JSONL (v1 or v2 schema) and produces:
  1. A bin table: stated-confidence bucket -> realized win rate, n, shrinkage.
  2. A correction function for FUTURE calls:
       calibrated(p) = w * bin_rate + (1-w) * prior,  w = n/(n+k)
     (empirical-Bayes shrinkage; k=20 default -- thin bins lean on the prior)
  3. Writes wiki/maintenance/calibration/confidence-map.json:
       {"bins": [{"lo":70,"hi":79,"n":43,"realized":0.30,"calibrated":0.42}], ...}
     Consumers (/invest Phase L self-grading, score_ledger pop_est sanity) read
     this map instead of trusting raw stated confidence.

HONESTY BAR: with small n this map is INDICATIVE. The file carries n and a
generated-on date; consumers must not treat calibrated values as precise.
"""

import argparse
import json
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
K = 20  # shrinkage strength


def load(jsonl):
    rows = []
    with open(ROOT / jsonl if not Path(jsonl).is_absolute() else jsonl,
              encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--jsonl", required=True)
    ap.add_argument("--win-key", default="beats_spy",
                    help="v2 field; falls back to 'correct' (v1)")
    ap.add_argument("--horizon", type=int, default=None,
                    help="filter to one horizon if records carry it")
    args = ap.parse_args()

    rows = load(args.jsonl)
    if args.horizon is not None:
        rows = [r for r in rows if r.get("horizon") in (None, args.horizon)]
    graded = [r for r in rows if r.get("confidence") is not None
              and args.win_key in r]
    if len(graded) < 10:
        print(f"too few graded records with confidence ({len(graded)}); "
              "refusing to publish a calibrator this thin")
        return 2

    base_rate = sum(1 for r in graded if r[args.win_key]) / len(graded)
    bins = {}
    for r in graded:
        c = r["confidence"]
        lo = min(c // 10 * 10, 90)
        bins.setdefault((lo, lo + 9), []).append(r)

    out_bins = []
    for (lo, hi), rs in sorted(bins.items()):
        n = len(rs)
        realized = sum(1 for r in rs if r[args.win_key]) / n
        w = n / (n + K)
        calibrated = round(w * realized + (1 - w) * base_rate, 3)
        out_bins.append({"lo": lo, "hi": hi, "n": n,
                         "stated_mid": round((lo + hi + 1) / 2),
                         "realized": round(realized, 3),
                         "calibrated": calibrated})

    payload = {
        "_comment": ("GENERATED by tools/confidence-calibrator.py -- empirical-Bayes"
                     " shrinkage of realized bin win-rates toward base rate (k=%d)."
                     " INDICATIVE ONLY at current sample sizes." % K),
        "generated": date.today().isoformat(),
        "source": str(args.jsonl),
        "win_key": args.win_key,
        "horizon": args.horizon,
        "n": len(graded),
        "base_rate": round(base_rate, 3),
        "k": K,
        "bins": out_bins,
    }
    outdir = ROOT / "wiki" / "maintenance" / "calibration"
    outdir.mkdir(parents=True, exist_ok=True)
    outp = outdir / "confidence-map.json"
    outp.write_text(json.dumps(payload, indent=1), encoding="utf-8", newline="\n")

    md = ["---",
          "aliases: [confidence-calibration-map]",
          "categories: [wiki]",
          "type: report",
          "status: active",
          f"created: {date.today().isoformat()}",
          f"updated: {date.today().isoformat()}",
          "tags: [topic/meta]",
          'related: ["[[calibration-2026-08-23]]"]',
          "---", "",
          "# Confidence calibration map (GENERATED %s)" % date.today().isoformat(), "",
          f"Source: {args.jsonl} (n={len(graded)}, base rate {base_rate:.0%}, "
          f"win key `{args.win_key}`). Shrinkage k={K}.", "",
          "| stated | n | realized | calibrated |", "|---|---|---|---|"]
    for b in out_bins:
        md.append(f"| {b['lo']}-{b['hi']} | {b['n']} | {b['realized']:.0%} "
                  f"| **{b['calibrated']:.0%}** |")
    md += ["", "Future calls quoting X% confidence should be READ at the calibrated",
           "value; generators may consult confidence-map.json programmatically.", ""]
    (outdir / "confidence-map-2026.md").write_text(
        "\n".join(md), encoding="utf-8", newline="\n")

    print(f"calibrated map -> {outp.relative_to(ROOT)}")
    for b in out_bins:
        print(f"  {b['lo']:>2}-{b['hi']:<3} n={b['n']:<3} realized={b['realized']:.0%} "
              f"-> calibrated={b['calibrated']:.0%}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
