#!/usr/bin/env python3
"""
gen-codex-config.py -- Mission Four (2026-05-15)

Generates .codex/config.toml from .claude/settings.json.

Per V3 verified (developers.openai.com/codex/hooks): Codex supports 6 lifecycle
events (SessionStart, PreToolUse, PermissionRequest, PostToolUse, UserPromptSubmit,
Stop). PreCompact is NOT supported -- mission's Stop-hook variant calls
pre-compact.py first as workaround.

Per V2 verified (developers.openai.com/codex/subagents): agents.max_threads default
6 (mission's "9" target NOT documented).

Per V5 verified (developers.openai.com/codex/mcp): MCP servers configured at
[mcp_servers.<name>] in config.toml; transports STDIO + Streamable HTTP (no SSE).

Translation rules:
  Claude settings.json hook chain -> Codex config.toml [hooks.<event>] sections
  Each command wrapped with tools/lib/engine-detect.sh (sets OSANWE_ENGINE)
  PreCompact event dropped with comment noting Stop-hook compensation
  Bash and python commands preserved verbatim (Codex inherits PATH)

Idempotent re-runs: --check exit 1 on divergence.
"""
import argparse
import json
import os
import sys
from pathlib import Path

VAULT_ROOT = Path(os.environ.get("VAULT_ROOT", os.getcwd()))
SOURCE = VAULT_ROOT / ".claude" / "settings.json"
TARGET = VAULT_ROOT / ".codex" / "config.toml"

# Codex events that do NOT exist. Adoptions and rationale:
#   - PreCompact: V3 verified absent
#   - PostCompact: Feature 3 audit adoption 2026-05-21
#   - PostToolUseFailure: Feature 4 audit adoption 2026-05-21
#   - SubagentStart / SubagentStop: Feature 7 audit adoption 2026-05-21
# All documented as continuity/forensics gaps; manual scrape required for parity.
DROPPED_EVENTS = {
    "PreCompact",
    "PostCompact",
    "PostToolUseFailure",
    "SubagentStart",
    "SubagentStop",
}

# Per-event compensation notes emitted into generated .codex/config.toml.
# Default falls back to "no Codex workaround documented" for unknown events.
COMPENSATION_NOTES = {
    "PreCompact": ".codex/hooks/stop.sh invokes pre-compact.py first as workaround",
    "PostCompact": "known continuity gap (no Codex compaction event); hot.md still loaded at SessionStart via tools/session-start.sh",
    "PostToolUseFailure": "no Codex event for tool-failure forensics; manual transcript scrape via .codex/transcripts/ required for failure pattern analysis",
    "SubagentStart": "no Codex event for subagent dispatch start; manual .codex/transcripts/ scrape required for subagent telemetry",
    "SubagentStop": "no Codex event for subagent dispatch stop; manual .codex/transcripts/ scrape required for subagent telemetry",
}

# Event-name translation: Claude hook event -> Codex section key
# (per V3, events appear with the same camelCase names; preserved here)
EVENT_NAMES = {
    "SessionStart": "SessionStart",
    "PreToolUse": "PreToolUse",
    "PostToolUse": "PostToolUse",
    "UserPromptSubmit": "UserPromptSubmit",
    "Stop": "Stop",
    # PermissionRequest is a Codex bonus; no direct Claude equivalent (covered separately)
}

ENGINE_DETECT_WRAPPER = str(Path(os.environ.get("VAULT_ROOT", os.getcwd())) / "tools" / "lib" / "engine-detect.sh")


def toml_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render_hook_array(commands: list[dict]) -> list[str]:
    """Render list of {command, timeout} dicts as TOML array-of-tables lines."""
    lines = []
    for cmd in commands:
        c = cmd.get("command", "")
        t = cmd.get("timeout", 0)
        # Wrap command with engine-detect.sh
        # Original command e.g. "python ${VAULT_ROOT}/tools/wikilink-check.py"
        # Wrapped: "bash <wrapper> python ${VAULT_ROOT}/tools/wikilink-check.py"
        wrapped = f"bash {ENGINE_DETECT_WRAPPER} {c}"
        lines.append("[[hooks." + cmd["_event"] + "]]")
        lines.append(f'  command = "{toml_escape(wrapped)}"')
        if t:
            lines.append(f"  timeout = {t}")
        if "_matcher" in cmd and cmd["_matcher"]:
            lines.append(f'  matcher = "{toml_escape(cmd["_matcher"])}"')
        lines.append("")
    return lines


def generate_toml(claude_settings: dict) -> str:
    """Generate the .codex/config.toml content."""
    lines = [
        "# Generated by tools/gen-codex-config.py (Mission Four, 2026-05-15)",
        "# Source: .claude/settings.json",
        "# DO NOT EDIT this file directly. Edit settings.json and re-run the generator.",
        "#",
        "# Per V3 verified: PreCompact lifecycle MISSING under Codex; .codex/hooks/stop.sh",
        "# invokes .claude/hooks/pre-compact.py first as workaround.",
        "# Per V2 verified: agents.max_threads default 6 (no docs basis for higher).",
        "",
        "# Subagent dispatch concurrency",
        "[agents]",
        "max_threads = 6  # V2 documented default; bump deferred until docs publish guidance",
        "",
    ]

    # Build hook chain
    hook_chain = []
    claude_hooks = claude_settings.get("hooks", {})
    for claude_event, entries in claude_hooks.items():
        if claude_event in DROPPED_EVENTS:
            lines.append(f"# {claude_event} dropped: not supported under Codex")
            note = COMPENSATION_NOTES.get(claude_event, "no Codex workaround documented")
            lines.append(f"# Compensation: {note}")
            lines.append("")
            continue
        codex_event = EVENT_NAMES.get(claude_event)
        if not codex_event:
            continue
        for entry in entries:
            matcher = entry.get("matcher", "")
            for h in entry.get("hooks", []):
                cmd = h.get("command", "")
                # PreCompact-as-Stop workaround: route Stop via .codex/hooks/stop.sh
                # so pre-compact.py runs first (V3: Codex lacks PreCompact lifecycle).
                # The Codex stop.sh internally invokes the original stop-pr-and-audit.sh.
                if codex_event == "Stop" and "stop-pr-and-audit.sh" in cmd:
                    cmd = "bash ${VAULT_ROOT}/tools/../.codex/hooks/stop.sh"
                hook_chain.append({
                    "_event": codex_event,
                    "_matcher": matcher,
                    "command": cmd,
                    "timeout": h.get("timeout", 0),
                })

    # Codex Stop variant: prepend pre-compact.py call (Track 2 PreCompact workaround)
    # Mark the variant explicitly with a comment block
    lines.append("# === Hooks ===")
    lines.append("# All commands wrapped with tools/lib/engine-detect.sh (sets OSANWE_ENGINE)")
    lines.append("")
    lines.extend(render_hook_array(hook_chain))

    # Stop-hook PreCompact workaround: prepend pre-compact.py invocation
    lines.append("# === PreCompact workaround (Track 2; lifecycle event missing under Codex) ===")
    lines.append("# .codex/hooks/stop.sh wraps pre-compact.py + stop-pr-and-audit.sh in sequence")
    lines.append("# Edit .codex/hooks/stop.sh to adjust ordering or add Codex-specific Stop logic")
    lines.append("")

    # MCP servers section (placeholder; user populates as needed per V5)
    lines.append("# === MCP servers (V5: STDIO + Streamable HTTP, no SSE) ===")
    lines.append("# Example:")
    lines.append("# [mcp_servers.example]")
    lines.append('# command = "node"')
    lines.append('# args = ["/path/to/server.js"]')
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate .codex/config.toml from .claude/settings.json")
    parser.add_argument("--check", action="store_true", help="Idempotency check: exit 1 if divergence")
    args = parser.parse_args()

    if not SOURCE.exists():
        print(f"ERROR: source not found: {SOURCE}", file=sys.stderr)
        return 2
    settings = json.loads(SOURCE.read_text(encoding="utf-8"))
    new_content = generate_toml(settings)

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    if TARGET.exists() and TARGET.read_text(encoding="utf-8") == new_content:
        print(f"gen-codex-config: {TARGET.name} unchanged (idempotent)", file=sys.stderr)
        return 0
    if args.check:
        print(f"CHECK FAILED: {TARGET.name} would be regenerated", file=sys.stderr)
        return 1
    TARGET.write_text(new_content, encoding="utf-8")
    hook_count = sum(len(e.get("hooks", []))
                     for entries in settings.get("hooks", {}).values()
                     for e in entries)
    print(f"gen-codex-config: {TARGET.name} generated ({hook_count} hooks across "
          f"{len(settings.get('hooks',{}))} Claude events; PreCompact dropped)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
