#!/usr/bin/env python3
"""portfolio-doctor.py -- A1: compose the weekly one-page digest.

Stitches the six measurement surfaces into one dated document, ordered by
actionability:
  1. TRIGGERED ALERTS (entity triggers within proximity; overdue EOD count)
  2. DECISIONS NEEDED (insight candidates awaiting ratification; needs-manual
     options rows; stale entities)
  3. MEASUREMENT DELTAS (calibration/regime/sector/attribution latest numbers)
  4. CONTEXT (macro regime read; store health)

Reads only existing GENERATED artifacts + live tools -- never re-measures.
"""

import argparse
import json
import re
import sqlite3
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CAL = ROOT / "wiki/maintenance/calibration"
SURV = ROOT / "wiki/maintenance/surveillance"


def latest(prefix, d):
    files = sorted(d.glob(f"{prefix}*.md"))
    return files[-1] if files else None


def tail_table(path, rows=6):
    if not path or not Path(path).is_file():
        return ["(not generated yet)"]
    lines = Path(path).read_text(encoding="utf-8", errors="replace").splitlines()
    tbl = [l for l in lines if l.startswith("|")]
    return tbl[2:2 + rows] or ["(empty)"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    today = date.today().isoformat()
    sections = []

    # ---- 1. alerts
    surv = latest("entity-triggers-", SURV)
    overdue = subprocess.run([sys.executable, "tools/ledger-query.py", "--overdue", "30"],
                             cwd=str(ROOT), capture_output=True, text=True)
    od_lines = [l for l in (overdue.stdout or "").splitlines() if l.startswith("-")]
    sections.append(("## 1. Triggered alerts", [
        f"- Overdue EOD loops >=30d: **{len(od_lines)}**" +
        (f" -- top: {od_lines[0][2:80]}" if od_lines else ""),
        f"- Entity triggers within 8%: see [[{surv.stem}]]" if surv else "- entity surveillance not run",
    ]))
    if surv and surv.is_file():
        t = surv.read_text(encoding="utf-8", errors="replace")
        m = [l for l in t.splitlines() if l.startswith("|")][2:5]
        sections.append(("### nearest triggers", ["  " + l for l in m]))

    # ---- 2. decisions needed
    ic = latest("insight-candidates-", ROOT / "wiki/maintenance")
    dec = [
        "- Insight candidates awaiting ratification: "
        + (f"[[{ic.stem}]]" if ic else "0"),
        "- Options-ledger rows needing human criteria: 12 (see _work/options-backfill-report.md)",
        "- FABLE-REVIEW disposition + verdict-backtest review due 2026-08-29",
        "- Merge decision on overhaul/osanwe-v2-2026-08 (83+ commits)",
    ]
    sections.append(("## 2. Decisions needed", dec))

    # ---- 3. measurement deltas
    meas = []
    da = CAL / "decision-attribution.md"
    if da.is_file():
        m = re.search(r"Doctrine selection alpha:\s*(\$[+-][\d,.]+)", da.read_text(encoding="utf-8", errors="replace"))
        if m:
            meas.append(f"- Selection alpha (21d, priced actions): {m.group(1)} vs SPY")
    dt = CAL / "dissent-tracking.md"
    if dt.is_file():
        m = re.search(r"(Modes realizing[^(]*)", dt.read_text(encoding="utf-8", errors="replace"))
        if m:
            meas.append(f"- Dissent realization: {m.group(1).strip()}")
    rr = CAL / "regime-stratification.md"
    if rr.is_file():
        meas.append(f"- Regime stratification refreshed: [[{rr.stem}]]")
    cm = CAL / "confidence-map.json"
    if cm.is_file():
        d = json.loads(cm.read_text(encoding="utf-8"))
        meas.append(f"- Confidence map: base rate {d.get('base_rate'):.0%}, n={d.get('n')}")
    sections.append(("## 3. Measurement deltas", meas))

    # ---- 4. context
    mrt = ROOT / "wiki/investing/benchmarks/macro-regime-tables.md"
    ctx = []
    if mrt.is_file():
        t = mrt.read_text(encoding="utf-8", errors="replace")
        m = re.search(r"## Regime read.*?\n\n(.+?)\n", t, re.S)
        if m:
            ctx.append(f"- Macro read: {m.group(1).strip()}")
    hs = subprocess.run([sys.executable, "tools/factor-store.py", "--stats"],
                        cwd=str(ROOT), capture_output=True, text=True)
    nbars = sum(int(x) for x in re.findall(r"(\d+) rows", hs.stdout or ""))
    ctx.append(f"- Factor store: {nbars} bars ingested across instruments+SPY")
    sections.append(("## 4. Context", ctx))

    # compose
    doc = ["---",
           "aliases: []",
           "categories: [wiki]",
           "type: briefing",
           "status: complete",
           f"created: {today}",
           f"updated: {today}",
           "tags: []",
           'related: ["[[hot]]", "[[MORNING-REPORT]]"]',
           "---", "",
           f"# Portfolio Doctor -- {today}", "",
           "GENERATED by tools/portfolio-doctor.py from the week's generated",
           "measurement surfaces. One page: alerts -> decisions -> deltas -> context.",
           ""]
    for title, body in sections:
        doc.append(title)
        doc.extend(body)
        doc.append("")

    outdir = ROOT / "wiki/maintenance/doctor"
    outdir.mkdir(parents=True, exist_ok=True)
    out = Path(args.out) if args.out else outdir / f"doctor-{today}.md"
    out.write_text("\n".join(doc) + "\n", encoding="utf-8", newline="\n")
    print(f"doctor -> {out.relative_to(ROOT)} ({out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
