#!/usr/bin/env python3
"""Self-test for .agents/scripts/gen-roles.py (audit defects D43 / D29).

gen-roles.py turns every file in .agents/roles/ into a .claude/agents/ wrapper.
Three of those role files -- lane-editor, lane-extractor and lane-researcher --
are relay worker system prompts with no frontmatter at all: tools/relay.py and
config/local-lane.json load them BY PATH, byte-identically, and they were never
meant to be Claude Code agents. The generator emitted them anyway, producing
wrapper files that open with "---" immediately followed by "---". An agent file
with no name, description or tools has nothing to register, so the harness skips
it -- leaving three dead files that read as live agents.

A role file with no frontmatter is therefore not an agent definition, and the
generator should not claim it is. These cases run the real script inside a
throwaway tree: a role with frontmatter still generates, a role without one
generates nothing, a stale generated wrapper for such a role is cleaned up, and
a hand-authored file (no GENERATED marker) is never touched.

Framework: unittest stdlib (pytest not installed; per tools/ convention).
Run: py tools/test-gen-roles.py
"""
import os
import shutil
import subprocess
import sys
import tempfile
import unittest

TOOLS = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(TOOLS)
SCRIPT_SRC = os.path.join(REPO, ".agents", "scripts", "gen-roles.py")

ROLE_WITH_FM = """---
name: demo-agent
description: "A demo agent used only by this test."
tools: Read, Grep
model: sonnet
---

## Role Body

# demo-agent

Body text.
"""

ROLE_NO_FM = """# relay-only -- role prompt for the relay worker

Loaded by tools/relay.py as the system message, byte-identically.
"""


class TestGenRoles(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp(prefix="gen-roles-test-")
        self.roles = os.path.join(self.tmp, ".agents", "roles")
        self.agents = os.path.join(self.tmp, ".claude", "agents")
        scripts = os.path.join(self.tmp, ".agents", "scripts")
        for d in (self.roles, self.agents, scripts):
            os.makedirs(d)
        self.script = os.path.join(scripts, "gen-roles.py")
        shutil.copyfile(SCRIPT_SRC, self.script)
        self.write_role("demo-agent.md", ROLE_WITH_FM)
        self.write_role("relay-only.md", ROLE_NO_FM)

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def write_role(self, name, text):
        with open(os.path.join(self.roles, name), "w", encoding="utf-8", newline="\n") as f:
            f.write(text)

    def write_wrapper(self, name, text):
        with open(os.path.join(self.agents, name), "w", encoding="utf-8", newline="\n") as f:
            f.write(text)

    def wrapper(self, name):
        p = os.path.join(self.agents, name)
        if not os.path.isfile(p):
            return None
        with open(p, encoding="utf-8", newline="") as f:
            return f.read()

    def run_gen(self, *args):
        return subprocess.run([sys.executable, self.script] + list(args),
                              capture_output=True, text=True)

    def test_role_with_frontmatter_still_generates(self):
        out = self.run_gen()
        self.assertEqual(out.returncode, 0, out.stderr)
        w = self.wrapper("demo-agent.md")
        self.assertIsNotNone(w)
        self.assertIn("name: demo-agent", w)
        self.assertIn("tools: Read, Grep", w)
        self.assertIn("GENERATED by", w)

    def test_role_without_frontmatter_is_not_emitted(self):
        # D43: this used to write a file starting "---" then "---".
        self.run_gen()
        self.assertIsNone(self.wrapper("relay-only.md"))

    def test_stale_empty_wrapper_is_removed(self):
        dead = ('---\n---\n<!-- GENERATED by .agents/scripts/gen-roles.py from '
                '.agents/roles/relay-only.md -- DO NOT EDIT (edit the role file, '
                're-run gen-roles) -->\n\n# relay-only\n')
        self.write_wrapper("relay-only.md", dead)
        out = self.run_gen()
        self.assertEqual(out.returncode, 0, out.stderr)
        self.assertIsNone(self.wrapper("relay-only.md"))

    def test_check_reports_a_stale_wrapper_then_passes_once_clean(self):
        dead = ('---\n---\n<!-- GENERATED by .agents/scripts/gen-roles.py from '
                '.agents/roles/relay-only.md -- DO NOT EDIT (edit the role file, '
                're-run gen-roles) -->\n\n# relay-only\n')
        self.write_wrapper("relay-only.md", dead)
        self.assertEqual(self.run_gen("--check").returncode, 1)
        self.run_gen()
        self.assertEqual(self.run_gen("--check").returncode, 0)

    def test_hand_authored_file_is_never_deleted(self):
        hand = '---\nname: relay-only\ndescription: "hand written"\n---\n\nbody\n'
        self.write_wrapper("relay-only.md", hand)
        out = self.run_gen()
        self.assertEqual(out.returncode, 0, out.stderr)
        self.assertEqual(self.wrapper("relay-only.md"), hand)


if __name__ == "__main__":
    unittest.main(verbosity=2)
