#!/usr/bin/env python3
"""usage-ledger.py -- measured per-skill / per-subagent usage from vault evidence.

Sources (all read-only):
  1. Calendar/daily/*.md "## Log" sections, lines of the form `- [HH:MM] ...`
     counting mentions of /<skill> (the prompt-log convention since 2026-04-20).
  2. Calendar/decisions/sessions-log.md "Skills invoked:" field tallies.
  3. .claude/state/subagent-telemetry-*.jsonl -> per-agent dispatch counts.

Outputs: wiki/maintenance/usage/usage-<YYYY-MM>.md + a JSON beside it.
Reconciles against mission C2; differences are findings, not errors.
"""

import json
import os
import re
import sys
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KNOWN_SKILLS = ["invest", "brief", "networth", "gate", "retro", "vault", "decide",
                "challenge", "ingest", "enrich", "spark", "consolidate", "deep",
                "local", "create-skill"]


def month_key(name):
    m = re.match(r"^(\d{4}-\d{2})", name)
    return m.group(1) if m else None


def scan_daily_logs():
    per_skill = defaultdict(Counter)   # skill -> {month: count}
    total_lines = 0
    ddir = ROOT / "Calendar" / "daily"
    for fn in sorted(os.listdir(ddir)):
        if not fn.endswith(".md"):
            continue
        month = month_key(fn)
        if not month:
            continue
        text = (ddir / fn).read_text(encoding="utf-8", errors="replace")
        sec = re.search(r"^## Log$(.*?)(?=^## |\Z)", text, re.M | re.S)
        if not sec:
            continue
        for line in sec.group(1).splitlines():
            # two coexisting Log-line formats:
            #   agent action:  - [HH:MM] did X
            #   prompt log:    - 2026-08-17T03:15:00 :: /invest ...
            if not (re.match(r"^\s*- \[\d{2}:\d{2}\]", line)
                    or re.match(r"^\s*- \d{4}-\d{2}-\d{2}", line)):
                continue
            total_lines += 1
            for sk in KNOWN_SKILLS:
                if re.search(r"/" + re.escape(sk) + r"\b", line):
                    per_skill[sk][month] += 1
    return per_skill, total_lines


def scan_sessions_log():
    text = ""
    p = ROOT / "Calendar" / "decisions" / "sessions-log.md"
    if p.is_file():
        text = p.read_text(encoding="utf-8", errors="replace")
    known = set(KNOWN_SKILLS)
    tally = Counter()
    for m in re.finditer(r"Skills invoked?:\s*(.+)", text):
        for sk in re.findall(r"/([a-z][a-z0-9-]+)", m.group(1)):
            if sk in known:
                tally[sk] += 1
    rows = len(re.findall(r"^### ", text, re.M))
    return dict(tally), rows


def scan_telemetry():
    counts = Counter()
    files = 0
    sdir = ROOT / ".claude" / "state"
    if not sdir.is_dir():
        return {}, 0
    for fn in os.listdir(sdir):
        if not fn.startswith("subagent-telemetry-") or not fn.endswith(".jsonl"):
            continue
        files += 1
        try:
            with open(sdir / fn, encoding="utf-8", errors="replace") as f:
                for line in f:
                    try:
                        rec = json.loads(line)
                    except Exception:
                        continue
                    # dispatches are 'start' records; stop records carry empty agent_type
                    if rec.get("event") != "start":
                        continue
                    name = rec.get("agent_type") or rec.get("label") or "?"
                    counts[str(name)] += 1
        except OSError:
            continue
    return dict(counts), files


def main():
    per_skill, log_lines = scan_daily_logs()
    sl_tally, sl_rows = scan_sessions_log()
    telem, tfiles = scan_telemetry()

    out_dir = ROOT / "wiki" / "maintenance" / "usage"
    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = date.today().strftime("%Y-%m")
    months = sorted({m for c in per_skill.values() for m in c} )
    md = ["---",
          "aliases: []",
          "categories: [wiki]",
          "type: report",
          "status: active",
          "created: %s" % date.today().isoformat(),
          "updated: %s" % date.today().isoformat(),
          "tags: [topic/meta]",
          'related: ["[[hot]]"]',
          "---", "",
          "# Usage ledger (generated %s)" % date.today().isoformat(), "",
          "GENERATED by tools/usage-ledger.py -- do not hand-edit.", "",
          "| skill | " + " | ".join(months) + " | total |", "|---|" + "---|" * (len(months) + 1)]
    grand = Counter()
    for sk in KNOWN_SKILLS:
        if sk not in per_skill and sk not in sl_tally:
            continue
        row = [str(per_skill[sk].get(m, 0)) for m in months]
        tot = sum(int(x) for x in row)
        grand[sk] = tot
        md.append("| /%s | " % sk + " | ".join(row) + f" | {tot} |")
    md += ["", "sessions-log rows: %d ; 'Skills invoked' mentions: %s" %
           (sl_rows, json.dumps(dict(sorted(sl_tally.items(), key=lambda kv: -kv[1])))), "",
           "subagent telemetry files: %d ; dispatches: %s" %
           (tfiles, json.dumps(dict(sorted(telem.items(), key=lambda kv: -kv[1])[:20]))), "",
           "daily prompt-lines scanned: %d" % log_lines, ""]
    (out_dir / f"usage-{stamp}.md").write_text("\n".join(md), encoding="utf-8")

    js = {"generated": date.today().isoformat(),
          "months": months,
          "per_skill_daily_logs": {k: dict(v) for k, v in per_skill.items()},
          "sessions_log_mentions": sl_tally,
          "subagent_dispatches": telem,
          "prompt_lines_scanned": log_lines}
    with open(out_dir / f"usage-{stamp}.json", "w", encoding="utf-8") as f:
        json.dump(js, f, indent=1)

    print(f"usage-ledger -> wiki/maintenance/usage/usage-{stamp}.md + .json")
    top = sorted(grand.items(), key=lambda kv: -kv[1])[:8]
    print("top by daily-log count:", top)
    print("telemetry dispatches:", sum(telem.values()), "across", tfiles, "files")


if __name__ == "__main__":
    sys.exit(main())
